### ISSUE TITLE
 dependency errors,unable to input

### ISSUE THREAD

**Issue by mikeyimer** [MrForExample/ComfyUI-AnimateAnyone-Evolved#1]
After installation, some components cannot be input, are undefined,I changed to ./python_embeded/python, which also caused xformer dependency errors.(![err1](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/assets/137673481/27f71c82-2368-49b5-ac15-a31d169fa6e2))

**Comment by MrForExample** [comment]
Please follow the [Install instruction](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved?tab=readme-ov-file#install-will-add-it-to-comfyui-manager-soon)

But in short, from what I can see in your screen shot, you need to download the clip model and put them in the `Your ComfyUI Root Directory\ComfyUI\models\clip_vision`, and put the files inside [Test Inputs](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/tree/main/_Example_Workflow/_Test_Inputs) into `Your ComfyUI Root Directory\ComfyUI\input`

And there is a chance I missed a few python libraries inside `requirement.txt`, since all the addon for the ComfyUI use the same python environment, so I may missed a few python package which is installed by other addons that I've installed, but ComfyUI console should tell you what package is missing, if you find it out, then please tell me, I'll add it to the `requirement.txt`, thanks :)

**Comment by mikeyimer** [comment]
Updating to the latest python dependencies solved my problem, it works, the only problem is that video-combine cannot display the video, no errors are reported

**Comment by MrForExample** [comment]
video-combine node is provided by [ComfyUI-VideoHelperSuite](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite)

You can consider update that package or ComfyUI see if it solves issue
